steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy streaming_gateway \
      --gen2 \
      --runtime=go125 \
      --region=us-central1 \
      --source=. \
      --entry-point=Handler \
      --trigger-http \
      --memory=256MB \
      --timeout=60 \
      --max-instances=1 \
      --no-allow-unauthenticated \
      --service-account=sa-invoker-cf@personal-project-dev-482704.iam.gserviceaccount.com \
      --quiet \
      --set-env-vars PROJECT_ID=personal-project-dev-482704,TOPIC_NAME=streming_event,API_KEY=test123
options:
  logging: CLOUD_LOGGING_ONLY