steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    gcloud functions deploy gateway-demo \
      --gen2 \
      --runtime=go121 \
      --region=asia-southeast2 \
      --source=./gateway \
      --entry-point=Handler \
      --trigger-http \
      --allow-unauthenticated \
      --memory=256MB \
      --timeout=60 \
      --set-env-vars PROJECT_ID=$PROJECT_ID,TOPIC_NAME=demo-event-stream,API_KEY=test123